// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_share/test/presentation/blocs/url_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_share/data/models/pending_url.dart' as _i4;
import 'package:mobile_share/data/repositories/local_url_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalUrlRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalUrlRepository extends _i1.Mock
    implements _i2.LocalUrlRepository {
  MockLocalUrlRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> addUrl(_i4.PendingUrl? url) =>
      (super.noSuchMethod(
            Invocation.method(#addUrl, [url]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> exists(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [url]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.PendingUrl>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.PendingUrl>>.value(
              <_i4.PendingUrl>[],
            ),
          )
          as _i3.Future<List<_i4.PendingUrl>>);

  @override
  _i3.Future<List<_i4.PendingUrl>> getUnsynced() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsynced, []),
            returnValue: _i3.Future<List<_i4.PendingUrl>>.value(
              <_i4.PendingUrl>[],
            ),
          )
          as _i3.Future<List<_i4.PendingUrl>>);

  @override
  _i3.Future<int> markAsSynced(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [ids]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
